# Generated by Django 4.0.2 on 2022-02-15 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_requestmodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RequestModel',
        ),
    ]
