# Generated by Django 4.0.2 on 2022-02-15 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_delete_requestmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='registeration',
            name='is_verified',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
