# Generated by Django 4.0.2 on 2022-02-18 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0007_donation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Voting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidate1', models.CharField(blank=True, max_length=50, null=True)),
                ('cantidate2', models.CharField(blank=True, max_length=50, null=True)),
                ('from_date', models.DateField(blank=True, null=True)),
                ('to_date', models.DateField(blank=True, null=True)),
                ('winner', models.CharField(blank=True, max_length=40, null=True)),
            ],
        ),
    ]
