# Generated by Django 4.0.2 on 2022-02-18 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0008_voting'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Voting',
        ),
    ]
