# Generated by Django 4.0.2 on 2022-02-18 19:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0010_voting'),
    ]

    operations = [
        migrations.AddField(
            model_name='voting',
            name='can1',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='can1', to='app1.registeration'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='voting',
            name='can2',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='can2', to='app1.registeration'),
            preserve_default=False,
        ),
    ]
