# Generated by Django 4.0.2 on 2022-03-10 16:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0014_rename_admin_superuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='uservote',
            name='voting',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.voting'),
        ),
    ]
