# Generated by Django 4.0.2 on 2022-03-10 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0015_uservote_voting'),
    ]

    operations = [
        migrations.AddField(
            model_name='voting',
            name='position',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
