# Generated by Django 4.1.2 on 2023-06-20 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0017_remove_voting_can1_remove_voting_can2_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registeration',
            name='is_voted',
        ),
    ]
